CREATE TABLE page_views (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id   BIGINT      NOT NULL REFERENCES brands (id) ON DELETE CASCADE,
    vehicle_id BIGINT      REFERENCES vehicles (id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_page_views_brand_created_at ON page_views (brand_id, created_at);
CREATE INDEX idx_page_views_created_at ON page_views (created_at);
CREATE INDEX idx_page_views_vehicle_id ON page_views (vehicle_id);
