CREATE TABLE banners (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(120),
    subtitle      VARCHAR(255),
    image_url     VARCHAR(500) NOT NULL,
    storage_path  VARCHAR(500) NOT NULL,
    link_url      VARCHAR(500),
    display_order INTEGER      NOT NULL DEFAULT 0,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_banners_active_order ON banners (active, display_order);
