CREATE TABLE vehicles (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id                  BIGINT         NOT NULL REFERENCES brands (id),
    category_id               BIGINT         NOT NULL REFERENCES categories (id),
    vehicle_type              VARCHAR(20)    NOT NULL,
    model                     VARCHAR(100)   NOT NULL,
    version                   VARCHAR(150)   NOT NULL,
    slug                      VARCHAR(220)   NOT NULL,
    year                      INTEGER        NOT NULL,
    mileage                   INTEGER        NOT NULL,
    price                     NUMERIC(12, 2) NOT NULL,
    promotional_price         NUMERIC(12, 2),
    fuel                      VARCHAR(20)    NOT NULL,
    transmission              VARCHAR(20)    NOT NULL,
    color                     VARCHAR(40),
    license_plate_last_digits VARCHAR(4),
    description               TEXT,
    status                    VARCHAR(20)    NOT NULL DEFAULT 'DISPONIVEL',
    featured                  BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at                TIMESTAMPTZ    NOT NULL,
    updated_at                TIMESTAMPTZ    NOT NULL,
    CONSTRAINT uq_vehicles_slug UNIQUE (slug),
    CONSTRAINT chk_vehicles_vehicle_type CHECK (vehicle_type IN ('CARRO', 'MOTO', 'CAMINHAO')),
    CONSTRAINT chk_vehicles_fuel CHECK (fuel IN ('FLEX', 'GASOLINA', 'ETANOL', 'DIESEL', 'HIBRIDO', 'ELETRICO', 'GNV')),
    CONSTRAINT chk_vehicles_transmission CHECK (transmission IN ('MANUAL', 'AUTOMATICO', 'AUTOMATIZADO', 'CVT', 'SEMI_AUTOMATICO')),
    CONSTRAINT chk_vehicles_status CHECK (status IN ('DISPONIVEL', 'RESERVADO', 'VENDIDO', 'INATIVO')),
    CONSTRAINT chk_vehicles_price_positive CHECK (price > 0),
    CONSTRAINT chk_vehicles_mileage_non_negative CHECK (mileage >= 0)
);

CREATE INDEX idx_vehicles_brand_id ON vehicles (brand_id);
CREATE INDEX idx_vehicles_category_id ON vehicles (category_id);
CREATE INDEX idx_vehicles_year ON vehicles (year);
CREATE INDEX idx_vehicles_price ON vehicles (price);
CREATE INDEX idx_vehicles_mileage ON vehicles (mileage);
CREATE INDEX idx_vehicles_status ON vehicles (status);
CREATE INDEX idx_vehicles_featured ON vehicles (featured);
CREATE INDEX idx_vehicles_vehicle_type ON vehicles (vehicle_type);
CREATE INDEX idx_vehicles_status_type_category ON vehicles (status, vehicle_type, category_id);
