CREATE TABLE vehicle_images (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id    BIGINT      NOT NULL REFERENCES vehicles (id) ON DELETE CASCADE,
    image_url     VARCHAR(500) NOT NULL,
    storage_path  VARCHAR(500) NOT NULL,
    is_primary    BOOLEAN     NOT NULL DEFAULT FALSE,
    display_order INTEGER     NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_vehicle_images_vehicle_id ON vehicle_images (vehicle_id);
