CREATE TABLE technical_specifications (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id           BIGINT NOT NULL REFERENCES vehicles (id) ON DELETE CASCADE,
    engine               VARCHAR(100),
    displacement         VARCHAR(50),
    horsepower           VARCHAR(50),
    torque               VARCHAR(50),
    traction             VARCHAR(50),
    urban_consumption    NUMERIC(5, 1),
    highway_consumption  NUMERIC(5, 1),
    fuel_tank_capacity   NUMERIC(5, 1),
    doors                INTEGER,
    seats                INTEGER,
    weight               NUMERIC(7, 1),
    length               NUMERIC(6, 1),
    width                NUMERIC(6, 1),
    height               NUMERIC(6, 1),
    CONSTRAINT uq_technical_specifications_vehicle_id UNIQUE (vehicle_id)
);
