CREATE TABLE dealership_settings (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dealership_name  VARCHAR(150) NOT NULL,
    logo_url         VARCHAR(500),
    whatsapp         VARCHAR(20)  NOT NULL,
    phone            VARCHAR(20),
    instagram        VARCHAR(100),
    address          VARCHAR(200),
    city             VARCHAR(100),
    state            VARCHAR(2),
    opening_hours    VARCHAR(200),
    description      TEXT,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL
);
