CREATE TABLE contact_leads (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id    BIGINT REFERENCES vehicles (id) ON DELETE SET NULL,
    vehicle_label VARCHAR(255) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_contact_leads_vehicle_id ON contact_leads (vehicle_id);
CREATE INDEX idx_contact_leads_created_at ON contact_leads (created_at);
