package com.concessionaria.vehicle;

import com.concessionaria.brand.Brand;
import com.concessionaria.brand.BrandRepository;
import com.concessionaria.category.Category;
import com.concessionaria.category.CategoryRepository;
import com.concessionaria.vehicle.dto.VehicleFilter;
import com.concessionaria.vehicle.spec.VehicleSpecifications;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.math.BigDecimal;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Verifies {@link VehicleSpecifications} filtering/pagination/sorting against a
 * real PostgreSQL instance (Testcontainers) — the same database engine used in
 * production — rather than an in-memory substitute, since the specifications
 * rely on Postgres-compatible SQL generated by Hibernate's Criteria API.
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@Testcontainers
class VehicleRepositoryTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16-alpine");

    @DynamicPropertySource
    static void configureDatasource(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", postgres::getJdbcUrl);
        registry.add("spring.datasource.username", postgres::getUsername);
        registry.add("spring.datasource.password", postgres::getPassword);
    }

    @Autowired
    private VehicleRepository vehicleRepository;

    @Autowired
    private BrandRepository brandRepository;

    @Autowired
    private CategoryRepository categoryRepository;

    private Brand toyota;
    private Brand honda;
    private Category sedan;
    private Category suv;

    @BeforeEach
    void setUp() {
        toyota = brandRepository.save(brand("Toyota"));
        honda = brandRepository.save(brand("Honda"));
        sedan = categoryRepository.save(category("Sedan"));
        suv = categoryRepository.save(category("SUV"));

        vehicleRepository.save(vehicle(toyota, sedan, "Corolla", "XEi", 2023,
                new BigDecimal("129900"), 15000, VehicleStatus.DISPONIVEL, "corolla-xei-2023"));
        vehicleRepository.save(vehicle(honda, suv, "HR-V", "EXL", 2022,
                new BigDecimal("150000"), 20000, VehicleStatus.DISPONIVEL, "hrv-exl-2022"));
        vehicleRepository.save(vehicle(toyota, sedan, "Corolla", "GLi", 2019,
                new BigDecimal("80000"), 60000, VehicleStatus.VENDIDO, "corolla-gli-2019"));
    }

    @Test
    void withFilter_byBrandId_returnsOnlyVehiclesFromThatBrand() {
        VehicleFilter filter = filterWith(f -> f.brandId(toyota.getId()));

        Page<Vehicle> page = vehicleRepository.findAll(VehicleSpecifications.withFilter(filter), PageRequest.of(0, 10));

        assertThat(page.getTotalElements()).isEqualTo(2);
        assertThat(page.getContent()).allMatch(v -> v.getBrand().getId().equals(toyota.getId()));
    }

    @Test
    void withFilter_byStatus_excludesVehiclesWithOtherStatuses() {
        VehicleFilter filter = filterWith(f -> f.statuses(Set.of(VehicleStatus.DISPONIVEL)));

        Page<Vehicle> page = vehicleRepository.findAll(VehicleSpecifications.withFilter(filter), PageRequest.of(0, 10));

        assertThat(page.getTotalElements()).isEqualTo(2);
        assertThat(page.getContent()).noneMatch(v -> v.getStatus() == VehicleStatus.VENDIDO);
    }

    @Test
    void withFilter_byFreeTextQuery_matchesModelCaseInsensitively() {
        VehicleFilter filter = filterWith(f -> f.q("corolla"));

        Page<Vehicle> page = vehicleRepository.findAll(VehicleSpecifications.withFilter(filter), PageRequest.of(0, 10));

        assertThat(page.getTotalElements()).isEqualTo(2);
        assertThat(page.getContent()).allMatch(v -> v.getModel().equalsIgnoreCase("Corolla"));
    }

    @Test
    void withFilter_byFreeTextQuery_matchesBrandName() {
        VehicleFilter filter = filterWith(f -> f.q("honda"));

        Page<Vehicle> page = vehicleRepository.findAll(VehicleSpecifications.withFilter(filter), PageRequest.of(0, 10));

        assertThat(page.getTotalElements()).isEqualTo(1);
        assertThat(page.getContent().get(0).getBrand().getName()).isEqualTo("Honda");
    }

    @Test
    void withFilter_byPriceRange_returnsOnlyVehiclesWithinRange() {
        VehicleFilter filter = filterWith(f -> f
                .minPrice(new BigDecimal("100000"))
                .maxPrice(new BigDecimal("140000")));

        Page<Vehicle> page = vehicleRepository.findAll(VehicleSpecifications.withFilter(filter), PageRequest.of(0, 10));

        assertThat(page.getTotalElements()).isEqualTo(1);
        assertThat(page.getContent().get(0).getModel()).isEqualTo("Corolla");
        assertThat(page.getContent().get(0).getVersion()).isEqualTo("XEi");
    }

    @Test
    void withFilter_byMaxMileage_excludesHighMileageVehicles() {
        VehicleFilter filter = filterWith(f -> f.maxMileage(25000));

        Page<Vehicle> page = vehicleRepository.findAll(VehicleSpecifications.withFilter(filter), PageRequest.of(0, 10));

        assertThat(page.getTotalElements()).isEqualTo(2);
    }

    @Test
    void findAll_respectsPageSizeAndReportsTotalPages() {
        Page<Vehicle> page = vehicleRepository.findAll(
                VehicleSpecifications.withFilter(filterWith(f -> f)), PageRequest.of(0, 1));

        assertThat(page.getContent()).hasSize(1);
        assertThat(page.getTotalElements()).isEqualTo(3);
        assertThat(page.getTotalPages()).isEqualTo(3);
    }

    @Test
    void findAll_sortsByPriceAscending() {
        Page<Vehicle> page = vehicleRepository.findAll(
                VehicleSpecifications.withFilter(filterWith(f -> f)),
                PageRequest.of(0, 10, Sort.by(Sort.Direction.ASC, "price")));

        assertThat(page.getContent()).extracting(Vehicle::getPrice)
                .isSortedAccordingTo(BigDecimal::compareTo);
        assertThat(page.getContent().get(0).getModel()).isEqualTo("Corolla");
        assertThat(page.getContent().get(0).getVersion()).isEqualTo("GLi");
    }

    @Test
    void existsBySlug_returnsTrue_onlyForRegisteredSlug() {
        assertThat(vehicleRepository.existsBySlug("corolla-xei-2023")).isTrue();
        assertThat(vehicleRepository.existsBySlug("does-not-exist")).isFalse();
    }

    @Test
    void existsBySlugAndIdNot_excludesTheGivenId() {
        Vehicle corolla = vehicleRepository.findBySlug("corolla-xei-2023").orElseThrow();

        assertThat(vehicleRepository.existsBySlugAndIdNot("corolla-xei-2023", corolla.getId())).isFalse();
        assertThat(vehicleRepository.existsBySlugAndIdNot("corolla-xei-2023", corolla.getId() + 1000)).isTrue();
    }

    @Test
    void findBySlug_eagerlyLoadsBrandAndCategory() {
        Vehicle vehicle = vehicleRepository.findBySlug("hrv-exl-2022").orElseThrow();

        assertThat(vehicle.getBrand().getName()).isEqualTo("Honda");
        assertThat(vehicle.getCategory().getName()).isEqualTo("SUV");
    }

    @Test
    void countByStatus_countsOnlyVehiclesWithThatStatus() {
        assertThat(vehicleRepository.countByStatus(VehicleStatus.DISPONIVEL)).isEqualTo(2);
        assertThat(vehicleRepository.countByStatus(VehicleStatus.VENDIDO)).isEqualTo(1);
        assertThat(vehicleRepository.countByStatus(VehicleStatus.RESERVADO)).isZero();
    }

    private Brand brand(String name) {
        Brand brand = new Brand();
        brand.setName(name);
        brand.setActive(true);
        return brand;
    }

    private Category category(String name) {
        Category category = new Category();
        category.setName(name);
        category.setActive(true);
        return category;
    }

    private Vehicle vehicle(Brand brand, Category category, String model, String version, int year,
                            BigDecimal price, int mileage, VehicleStatus status, String slug) {
        Vehicle vehicle = new Vehicle();
        vehicle.setBrand(brand);
        vehicle.setCategory(category);
        vehicle.setVehicleType(VehicleType.CARRO);
        vehicle.setModel(model);
        vehicle.setVersion(version);
        vehicle.setYear(year);
        vehicle.setMileage(mileage);
        vehicle.setPrice(price);
        vehicle.setFuel(FuelType.FLEX);
        vehicle.setTransmission(TransmissionType.AUTOMATICO);
        vehicle.setStatus(status);
        vehicle.setFeatured(false);
        vehicle.setSlug(slug);
        return vehicle;
    }

    private VehicleFilter filterWith(java.util.function.UnaryOperator<FilterBuilder> customizer) {
        return customizer.apply(new FilterBuilder()).build();
    }

    /** Small fluent builder so each test only sets the fields it cares about. */
    private static final class FilterBuilder {
        private Long brandId;
        private Long categoryId;
        private VehicleType vehicleType;
        private Integer minYear;
        private Integer maxYear;
        private BigDecimal minPrice;
        private BigDecimal maxPrice;
        private Integer maxMileage;
        private FuelType fuel;
        private TransmissionType transmission;
        private String q;
        private Set<VehicleStatus> statuses;

        FilterBuilder brandId(Long value) {
            this.brandId = value;
            return this;
        }

        FilterBuilder maxMileage(Integer value) {
            this.maxMileage = value;
            return this;
        }

        FilterBuilder minPrice(BigDecimal value) {
            this.minPrice = value;
            return this;
        }

        FilterBuilder maxPrice(BigDecimal value) {
            this.maxPrice = value;
            return this;
        }

        FilterBuilder q(String value) {
            this.q = value;
            return this;
        }

        FilterBuilder statuses(Set<VehicleStatus> value) {
            this.statuses = value;
            return this;
        }

        VehicleFilter build() {
            return new VehicleFilter(brandId, categoryId, vehicleType, minYear, maxYear, minPrice, maxPrice,
                    maxMileage, fuel, transmission, q, statuses);
        }
    }
}
